# Generated by Django 5.2.6 on 2025-10-22 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nomor Materi')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Materi')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Materi',
                'verbose_name_plural': 'Materi',
                'db_table': 'materi',
                'ordering': ['nomor'],
            },
        ),
        migrations.CreateModel(
            name='NilaiEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Nilai')),
                ('jumlah_soal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jumlah Soal')),
                ('jumlah_benar', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jumlah Benar')),
                ('waktu_pengerjaan', models.DurationField(blank=True, null=True)),
                ('tanggal_evaluasi', models.DateTimeField(auto_now_add=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi', to='belajar.materi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_evaluasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nilai Evaluasi',
                'verbose_name_plural': 'Nilai Evaluasi',
                'db_table': 'nilai_evaluasi',
                'ordering': ['-tanggal_evaluasi'],
                'unique_together': {('user', 'materi')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(blank=True, choices=[('kelas_2', 'Kelas 2'), ('kelas_3', 'Kelas 3')], max_length=50, null=True, verbose_name='Kelas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Pengguna',
                'verbose_name_plural': 'Profil Pengguna',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='StatistikPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_waktu_belajar', models.DurationField(default='0:00:00')),
                ('streak_hari', models.IntegerField(default=0, verbose_name='Streak Belajar (Hari)')),
                ('terakhir_aktif', models.DateTimeField(auto_now=True)),
                ('materi_favorit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='belajar.materi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistik Pengguna',
                'verbose_name_plural': 'Statistik Pengguna',
                'db_table': 'statistik_pengguna',
            },
        ),
        migrations.CreateModel(
            name='KemajuanBelajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selesai', models.BooleanField(default=False, verbose_name='Selesai')),
                ('tanggal_mulai', models.DateTimeField(auto_now_add=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('progress_persentase', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Progress (%)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kemajuan_belajar', to=settings.AUTH_USER_MODEL)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kemajuan', to='belajar.materi')),
            ],
            options={
                'verbose_name': 'Kemajuan Belajar',
                'verbose_name_plural': 'Kemajuan Belajar',
                'db_table': 'kemajuan_belajar',
                'ordering': ['user', 'materi__nomor'],
                'unique_together': {('user', 'materi')},
            },
        ),
        migrations.CreateModel(
            name='HasilJawabanEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_soal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nomor Soal')),
                ('soal', models.TextField(verbose_name='Soal')),
                ('jawaban_user', models.CharField(max_length=255, verbose_name='Jawaban User')),
                ('jawaban_benar', models.CharField(max_length=255, verbose_name='Jawaban Benar')),
                ('is_benar', models.BooleanField(default=False, verbose_name='Benar')),
                ('poin', models.FloatField(default=1.0, verbose_name='Poin')),
                ('tanggal_jawaban', models.DateTimeField(auto_now_add=True)),
                ('evaluasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_detail', to='belajar.nilaievaluasi')),
            ],
            options={
                'verbose_name': 'Detail Jawaban Evaluasi',
                'verbose_name_plural': 'Detail Jawaban Evaluasi',
                'db_table': 'hasil_jawaban_evaluasi',
                'ordering': ['evaluasi', 'nomor_soal'],
                'unique_together': {('evaluasi', 'nomor_soal')},
            },
        ),
    ]
