# Generated by Django 5.2.6 on 2025-10-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belajar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilaievaluasipermateri',
            name='user',
        ),
    ]
