# Generated by Django 5.2.6 on 2025-12-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belajar", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
        migrations.AddField(
            model_name="profile",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics",
                verbose_name="Foto Profil",
            ),
        ),
        migrations.AlterModelTable(
            name="profile",
            table=None,
        ),
    ]
