# Generated by Django 5.2.6 on 2025-10-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belajar', '0002_remove_nilaievaluasipermateri_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabanevaluasi',
            name='materi_soal',
            field=models.CharField(choices=[('materi_1', 'Materi 1'), ('materi_2', 'Materi 2'), ('materi_3', 'Materi 3'), ('materi_4', 'Materi 4'), ('materi_5', 'Materi 5'), ('materi_6', 'Materi 6')], help_text='Materi asal dari soal ini', max_length=50, verbose_name='Materi Soal'),
        ),
        migrations.AlterField(
            model_name='kemajuanbelajar',
            name='materi',
            field=models.CharField(choices=[('materi_1', 'Materi 1'), ('materi_2', 'Materi 2'), ('materi_3', 'Materi 3'), ('materi_4', 'Materi 4'), ('materi_5', 'Materi 5'), ('materi_6', 'Materi 6')], max_length=50, verbose_name='Materi'),
        ),
        migrations.AlterField(
            model_name='nilaievaluasipermateri',
            name='materi',
            field=models.CharField(choices=[('materi_1', 'Materi 1'), ('materi_2', 'Materi 2'), ('materi_3', 'Materi 3'), ('materi_4', 'Materi 4'), ('materi_5', 'Materi 5'), ('materi_6', 'Materi 6')], max_length=50, verbose_name='Materi'),
        ),
    ]
