# Generated by Django 5.2.6 on 2025-12-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belajar', '0003_nilaievaluasi_rekomendasi_materi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil Pengguna', 'verbose_name_plural': 'Profil Pengguna'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
