# Generated by Django 5.2.6 on 2026-01-10 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belajar', '0004_alter_profile_options_alter_profile_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Kuis')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Singkat')),
                ('kelas_target', models.CharField(choices=[('kelas_2', 'Kelas 2'), ('kelas_3', 'Kelas 3')], max_length=20, verbose_name='Untuk Kelas')),
                ('durasi_menit', models.IntegerField(default=10, help_text='Durasi dalam menit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktifkan Kuis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuis_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('benar', models.IntegerField()),
                ('salah', models.IntegerField()),
                ('tanggal_mengerjakan', models.DateTimeField(auto_now_add=True)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belajar.kuis')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kuis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoalKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('opsi_a', models.CharField(max_length=200, verbose_name='Pilihan A')),
                ('opsi_b', models.CharField(max_length=200, verbose_name='Pilihan B')),
                ('opsi_c', models.CharField(max_length=200, verbose_name='Pilihan C')),
                ('opsi_d', models.CharField(max_length=200, verbose_name='Pilihan D')),
                ('jawaban_benar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_soal', to='belajar.kuis')),
            ],
        ),
    ]
