# Generated by Django 5.2.6 on 2026-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belajar", "0005_kuis_riwayatkuis_soalkuis"),
    ]

    operations = [
        migrations.AddField(
            model_name="soalkuis",
            name="gambar",
            field=models.ImageField(
                blank=True,
                help_text="Upload gambar jika soal membutuhkan ilustrasi visual",
                null=True,
                upload_to="soal_images/",
                verbose_name="Gambar Soal",
            ),
        ),
    ]
